SASS-8051: Updated Dividends journey to display Excluded status when required
hmrc/income-tax-submission-frontend pull request #316
Opened 2024-05-03 14:42 UTC by ansahdavid

### Description
To enable Dividends to reflect on Excluded status when required

Linked to SASS-8051

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2024-05-09 13:31 UTC, ghousedev approved these changes

2024-05-09 15:10 UTC, kannanramakrishnan requested changes

2024-05-10 07:19 UTC, ansahdavid commented on app/views/OverviewPageView.scala.html
> +                } else if(isExcluded && appConfig.tailoringEnabled) {
Thanks for spotting this, I have removed in my next commit

2024-05-10 14:57 UTC, basotia approved these changes

2024-05-13 15:36 UTC, kannanramakrishnan submitted a review, later dismissed

2024-05-13 16:04 UTC, kannanramakrishnan approved these changes

2024-05-13 16:05 UTC, merged