[Sass 638] - Differentiate URL redirect link by actor
hmrc/income-tax-submission-frontend pull request #99
Opened 2021-04-19 12:25 UTC by dnyuar

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-638] https://jira.tools.tax.service.gov.uk/browse/SASS-607

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you addressed warnings where appropriate?

##### After PRs been Reviewed
- [ ]  Have you checked the PR Builder passes?
- [ ]  Have you checked for merge conflicts?
- [ ]  Have you checked code coverage isn’t lower than previously?

2021-04-20 15:21 UTC, robert-webb-hmrc commented
Can this be rebased please? Journey Tests currently don't pass due to url changes that affect this repo also

2021-04-20 15:32 UTC, dnyuar commented
branch been rebased

2021-04-20 15:58 UTC, robert-webb-hmrc commented on test/views/IVFailurePageSpec.scala
>      "render correctly when the user is an individual" should {
Both these cases are an individual user so should be (isAgent = false)

2021-04-20 15:59 UTC, robert-webb-hmrc requested changes
Please see above

2021-04-20 16:38 UTC, robert-webb-hmrc requested changes

2021-04-20 16:38 UTC, robert-webb-hmrc commented on test/controllers/SignOutControllerSpec.scala
> +        val responseF = controller.signOut(false)(request)
As mentioned on personal, could we consider having an agent case here?

2021-04-20 16:38 UTC, robert-webb-hmrc commented on test/views/helpers/BetaBarViewSpec.scala
> +        lazy val view = betaBar(isAgent)(fakeRequest, messages, appConfig)
As mentioned on personal, could we consider having an agent case here?

2021-04-20 16:38 UTC, robert-webb-hmrc commented
<img width="1499" alt="Screenshot 2021-04-20 at 17 26 06" src="https://user-images.githubusercontent.com/28566263/115433067-022a6f80-a1ff-11eb-9846-c502b6191f2a.png">

Can we address these warns please?

2021-04-21 09:02 UTC, robert-webb-hmrc approved these changes

2021-04-21 09:03 UTC, merged